apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
    - git:
        repoURL: https://github.com/d-cryptic/testing-argocd.git
        revision: HEAD
        files:
        - path: "git-generator-files-discovery/**/**/config.json"
  template:
    metadata:
      name: '{{cluster.name}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/d-cryptic/testing-argocd.git
        targetRevision: HEAD
        path: '{{cluster.path}}'
      destination:
        server: https://kubernetes.default.svc
        #server: '{{cluster.address}}'
        namespace: guestbook
