apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/d-cryptic/testing-argocd.git
        revision: main
        files:
        - path: "git-generator-files-discovery/**/**/config.json"
        - path: "git-generator-files-discovery/**/config.json"
        - path: "git-generator-files-discovery/**/**/**/config.json"
  template:
    metadata:
      name: '{{cluster.name}}-guestbook'
    spec:
      project: default
      source:
        # directory:
        #   recurse: true
        #   # exclude: '*, !*.*'
        #   # include: '*.yaml, *.yml'
        repoURL: https://github.com/d-cryptic/testing-argocd.git
        targetRevision: main
        path: '{{cluster.path}}'
      destination:
        server: https://kubernetes.default.svc
        #server: '{{cluster.address}}'
        namespace: argocd
