apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-image-update
  namespace: argocd
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    directory:
      exclude: '{config.json}'
      include: "{*.yml,*.yaml}"
    path: test2/git-dir-generator-example/argo-projects/argo-image-updater/
    repoURL: https://github.com/d-cryptic/testing-argocd.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
